### PR TITLE
Attempt to propagate a source throwable as a cause

### LINKED ISSUE #456: Consider adding actual `Throwable` as cause of `AssertionFailedError`
If I do
```kotlin
assertThat { somethingWhichFails() }
  .isFailure()
  .isInstanceOf(IllegalStateException::class)
```
and something _else_ fails throwing a different error type, all I see is:
```
expected to be instance of:<class java.lang.IllegalArgumentException> but had class:<class java.lang.AssertionError> (Failure(java.lang.AssertionError))
```
That isn't helpful!

It's a special casing, but in the case of the "actual" being a `Throwable` or a `Result` that's a failure, I think the `fail` function should add that `Throwable` as the cause to the `AssertionFailedError`.

This would provide me with the complete stacktrace of the unexpected failure and not just that the type or message disagrees.

We do this in Turbine and it's _excellent_. I would like it here, too!

### PR DESCRIPTION
**Pull request by JakeWharton**
This ensures that the full stacktrace can be seen to help identify the underlying source of a mismatch.

Consider the following two tests:
```kotlin
@Test fun demo1() {
  assertThat { someFunction() }
    .isFailure()
    .isInstanceOf(IllegalStateException::class)
}
@Test fun demo2() {
  assertThat { someFunction() }
    .isFailure()
    .hasMessage("failure!")
}
fun someFunction() {
  deepFunction()
}
fun deepFunction() {
  throw AssertionError("oh no!!!!!")
}
```
Demo 1's failure before:

    org.opentest4j.AssertionFailedError: expected to be instance of:<class java.lang.IllegalStateException> but had class:<class java.lang.AssertionError> (Failure(java.lang.AssertionError: oh no!!!!!))
    	at app//test.assertk.FailureTest.demo1(FailureTest.kt:56)
    	... 43 more

Demo 1's failure after:

    org.opentest4j.AssertionFailedError: expected to be instance of:<class java.lang.IllegalStateException> but had class:<class java.lang.AssertionError> (Failure(java.lang.AssertionError: oh no!!!!!))
    	at app//test.assertk.FailureTest.demo1(FailureTest.kt:56)
    	... 43 more
    Caused by: java.lang.AssertionError: oh no!!!!!
    	at test.assertk.FailureTest.deepFunction(FailureTest.kt:70)
    	at test.assertk.FailureTest.someFunction(FailureTest.kt:66)
    	at test.assertk.FailureTest.demo1(FailureTest.kt:54)
    	... 43 more

Demo 2's failure before:

    org.opentest4j.AssertionFailedError: expected [message]:<"[failure]!"> but was:<"[oh no!!!!]!"> (Failure(java.lang.AssertionError: oh no!!!!!))
    	at app//test.assertk.FailureTest.demo2(FailureTest.kt:61)
    	... 43 more

Demo 2's failure after:

    org.opentest4j.AssertionFailedError: expected [message]:<"[failure]!"> but was:<"[oh no!!!!]!"> (Failure(java.lang.AssertionError: oh no!!!!!))
    	at app//test.assertk.FailureTest.demo2(FailureTest.kt:62)
    	... 43 more
    Caused by: java.lang.AssertionError: oh no!!!!!
    	at test.assertk.FailureTest.deepFunction(FailureTest.kt:70)
    	at test.assertk.FailureTest.someFunction(FailureTest.kt:66)
    	at test.assertk.FailureTest.demo2(FailureTest.kt:60)
    	... 43 more

With the causes attached it's much easier to locate the source of the underlying problem.

Closes #456

### CODE REVIEW

File: assertk/src/commonMain/kotlin/assertk/assertions/support/support.kt [hunk 1]
```diff
@@ -76,10 +77,30 @@ fun <T> Assert<T>.fail(expected: Any?, actual: Any?) {
...
+            else -> null
+        }
+        if (cause == null) {
+            cause = when (val originating = context.originatingSubject) {
+                is Throwable -> originating
+                is Result<*> -> originating.exceptionOrNull()
+                else -> null
+            }
+        }
+    }
```
Comment (JakeWharton) [inline assertk/src/commonMain/kotlin/assertk/assertions/support/support.kt:97]: I started off with a bunch of clever functional shit here and it was an unreadable mess.

Comment (evant) [reply assertk/src/commonMain/kotlin/assertk/assertions/support/support.kt:97]: mood

File: assertk/src/commonMain/kotlin/assertk/failure.kt [hunk 2]
```diff
@@ -139,17 +140,29 @@ fun fail(error: AssertionError): Nothing {
 
 internal val NONE: Any = Any()
 
+// TODO Delete this before 1.0.
+@Deprecated("For binary compatibility", level = HIDDEN)
+fun fail(message: String, expected: Any? = NONE, actual: Any? = NONE): Nothing {
```
Comment (evant) [inline assertk/src/commonMain/kotlin/assertk/failure.kt:145]: I really haven't been bothering with binary compat before 1.0 (as opposed to source compat) with the assumption being that assertk is likely to be a leaf dependency instead of a transitive one. Would be happy to hear your thoughts though.

**Review by evant — COMMENTED** [review]
Overall I like it, the added context does seem helpful

File: assertk/src/commonMain/kotlin/assertk/failure.kt (hunk 2 above)
Comment (JakeWharton) [reply assertk/src/commonMain/kotlin/assertk/failure.kt:145]: It seemed like extremely low effort to retain so I included it. I could see a published library of assertions existing which might have used the function. That being said, if you don't want to set a precedent or anything I'm not tied to it.

Comment (evant) [reply assertk/src/commonMain/kotlin/assertk/failure.kt:145]: yeah it doesn't hurt anything, not sure I want to make binary compat a requirement for updates but I won't block merging this in on that.

**Review by evant — APPROVED** [review]
