### PR TITLE
Fixed issue where you couldn't select `isEqualTo` for nullable java strings

### LINKED ISSUE #58: Support for comparing Java Strings (nullable)
Given the Java class (with platform types):
`class Parson { public String name; }`
the following code
`assert(new Person().name).isEqualTo(new Person().name)`
picks the 'isEqualTo' from _strings.kt_, which requires not null type and fails with exception.
Adding a new method for the `String?` type should resolve the problem.
`fun Assert<String?>.isEqualTo(expected: String?)`

### PR DESCRIPTION
**Pull request by evant**
Fixes #58

### CODE REVIEW

File: src/main/kotlin/assertk/assertions/string.kt [hunk 1]
```diff
@@ -19,7 +19,7 @@ fun Assert<String>.hasLineCount(lineCount: Int) {
  * @param ignoreCase true to compare ignoring case, the default if false.
  * @see [isNotEqualTo]
  */
-fun Assert<String>.isEqualTo(other: String, ignoreCase: Boolean = false) {
+fun Assert<String?>.isEqualTo(other: String?, ignoreCase: Boolean) {
```
Comment (nishtahir) [inline src/main/kotlin/assertk/assertions/string.kt]: Is removing the default value a good idea? This causes the tests such as `                assert("").isNotEqualTo("test")` to invoke `Assert<T>.isNotEqualTo(expected: Any?)`.

Comment (evant) [reply src/main/kotlin/assertk/assertions/string.kt]: Hm, the extension method `String.isEqualTo(other, ignoreCase)` delegates to `equals()` so the behavior should be the same. But keeping the default would technically better match the signature.

Guess the question is if it's better to match the signature of the extension, or have `isEqualTo` have the same impl for all T.
