### PR TITLE
Fix `isDataClassEqualTo` not working with `data object`s

### LINKED ISSUE #551: `isDataClassEqualTo` passes when given different `data object`s
This test should fail, but it passes:
```kotlin
data object Example
data object AnotherExample

@Test
fun test() {
    assertThat(Example).isDataClassEqualTo(AnotherExample)
}
```
When using a normal `object`, it does fail since they aren't data classes:
```kotlin
object Example
object AnotherExample

@Test
fun test() {
    assertThat(Example).isDataClassEqualTo(AnotherExample)
    /*
    only supports data classes
        java.lang.IllegalArgumentException: only supports data classes
    */
}
```
And the different `data object`s correctly fail when using `isEqualTo`:
```kotlin
data object Example
data object AnotherExample

@Test
fun test() {
    assertThat(Example).isEqualTo(AnotherExample)
    /*
    Expected :[Another]Example
    Actual   :[]Example

    org.opentest4j.AssertionFailedError: expected:<[Another]Example> but was:<[]Example>
    */
}
```
I'd expect this to fail similarly to using `isEqualTo` or with a message that they're not supported. The current behavior gives the impression of a passing test.

### PR DESCRIPTION
**Pull request by VirtualParticle**
This fixes #551 by going right to `isEqualTo` if the passed value is a `data object`.

### CODE REVIEW

File: assertk/src/jvmMain/kotlin/assertk/assertions/any.kt [hunk 1]
```diff
@@ -82,7 +82,7 @@ fun <T : Any> Assert<T>.isDataClassEqualTo(expected: T) = given { actual ->
 private fun <T> Assert<T>.isDataClassEqualToImpl(expected: T, kclass: KClass<*>?): Unit = given { actual ->
     if (actual == expected) return
     val compareProps = actual != null && expected != null
-    if (compareProps && kclass != null && kclass.isData) {
+    if (compareProps && kclass != null && kclass.isData && kclass.objectInstance == null) {
```
Comment (VirtualParticle) [inline assertk/src/jvmMain/kotlin/assertk/assertions/any.kt:85]: This seemed like the best way to check if `kclass` is a `data object`, but there could be a better way.

Comment (evant) [reply assertk/src/jvmMain/kotlin/assertk/assertions/any.kt:85]: could we check the types directly? This should always fail if `expected::class != actual::class` right?

Comment (VirtualParticle) [reply assertk/src/jvmMain/kotlin/assertk/assertions/any.kt:85]: Sure, how does this look?
```kotlin
    val compareProps = actual != null && expected?.let { it::class } == kclass
    if (compareProps && kclass != null && kclass.isData) {
```

File: assertk/src/jvmMain/kotlin/assertk/assertions/any.kt [hunk 2]
```diff
@@ -81,7 +81,7 @@ fun <T : Any> Assert<T>.isDataClassEqualTo(expected: T) = given { actual ->
 
 private fun <T> Assert<T>.isDataClassEqualToImpl(expected: T, kclass: KClass<*>?): Unit = given { actual ->
     if (actual == expected) return
-    val compareProps = actual != null && expected != null
+    val compareProps = actual != null && expected?.let { it::class } == kclass
     if (compareProps && kclass != null && kclass.isData) {
```
Comment (VirtualParticle) [inline assertk/src/jvmMain/kotlin/assertk/assertions/any.kt:85]: This technically removes the `expected != null` check, but it's essentially still done since we check for equality with `kclass` which is then later checked not to be `null`.

**Review by evant — APPROVED** [review]
